set_property PACKAGE_PIN M1 [get_ports {light_en[0]}]
set_property PACKAGE_PIN N1 [get_ports {light_en[1]}]
set_property PACKAGE_PIN G2 [get_ports {light_en[2]}]
set_property PACKAGE_PIN N2 [get_ports {light_ew[0]}]
set_property PACKAGE_PIN K3 [get_ports {light_ew[1]}]
set_property PACKAGE_PIN M3 [get_ports {light_ew[2]}]
set_property PACKAGE_PIN K17 [get_ports {light_ns[0]}]
set_property PACKAGE_PIN M18 [get_ports {light_ns[1]}]
set_property PACKAGE_PIN J3 [get_ports {light_sn[0]}]
set_property PACKAGE_PIN L3 [get_ports {light_sn[1]}]
set_property PACKAGE_PIN M2 [get_ports {light_sn[2]}]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN U18 [get_ports reset]


set_property IOSTANDARD LVCMOS33 [get_ports {light_en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_en[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_ew[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_ew[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_ew[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_ns[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_ns[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_ns[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_sn[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_sn[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_sn[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_we[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_we[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_we[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_ws[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_ws[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_ws[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports sig1s]
set_property PACKAGE_PIN E19 [get_ports sig1s]

set_property PACKAGE_PIN B16 [get_ports {light_ws[2]}]
set_property PACKAGE_PIN M19 [get_ports {light_we[2]}]
set_property PACKAGE_PIN L17 [get_ports {light_we[1]}]
set_property PACKAGE_PIN N17 [get_ports {light_ns[2]}]
set_property PACKAGE_PIN P18 [get_ports {light_we[0]}]

set_property PACKAGE_PIN A16 [get_ports {light_ws[0]}]
set_property PACKAGE_PIN B15 [get_ports {light_ws[1]}]

set_property SLEW FAST [get_ports {light_en[2]}]
set_property SLEW FAST [get_ports {light_en[1]}]
set_property SLEW FAST [get_ports {light_en[0]}]
set_property SLEW FAST [get_ports {light_ew[2]}]
set_property SLEW FAST [get_ports {light_ew[1]}]
set_property SLEW FAST [get_ports {light_ew[0]}]
set_property SLEW FAST [get_ports {light_ns[2]}]
set_property SLEW FAST [get_ports {light_ns[1]}]
set_property SLEW FAST [get_ports {light_ns[0]}]
set_property SLEW FAST [get_ports {light_sn[2]}]
set_property SLEW FAST [get_ports {light_sn[1]}]
set_property SLEW FAST [get_ports {light_sn[0]}]
set_property SLEW FAST [get_ports {light_we[2]}]
set_property SLEW FAST [get_ports {light_we[1]}]
set_property SLEW FAST [get_ports {light_we[0]}]
set_property SLEW FAST [get_ports {light_ws[2]}]
set_property SLEW FAST [get_ports {light_ws[1]}]
set_property SLEW FAST [get_ports {light_ws[0]}]
set_property DRIVE 12 [get_ports {light_en[2]}]
set_property DRIVE 12 [get_ports {light_en[1]}]
set_property DRIVE 12 [get_ports {light_en[0]}]

set_property PACKAGE_PIN R2 [get_ports ht]
set_property IOSTANDARD LVCMOS33 [get_ports ht]

set_property PACKAGE_PIN T1 [get_ports mal]
set_property IOSTANDARD LVCMOS33 [get_ports mal]

set_property PACKAGE_PIN W2 [get_ports va]
set_property IOSTANDARD LVCMOS33 [get_ports va]

set_property PACKAGE_PIN U1 [get_ports vm]
set_property IOSTANDARD LVCMOS33 [get_ports vm]

set_property IOSTANDARD LVCMOS33 [get_ports {light_dt[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_dt[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_dt[0]}]
set_property PACKAGE_PIN L2 [get_ports {light_dt[2]}]
set_property PACKAGE_PIN J2 [get_ports {light_dt[1]}]
set_property PACKAGE_PIN A14 [get_ports {light_dt[0]}]
set_property PACKAGE_PIN R3 [get_ports pa]
set_property IOSTANDARD LVCMOS33 [get_ports pa]

set_property PACKAGE_PIN T2 [get_ports aw]
set_property IOSTANDARD LVCMOS33 [get_ports aw]

set_property PACKAGE_PIN W19 [get_ports at]
set_property IOSTANDARD LVCMOS33 [get_ports at]

